# Site settings
title: Yuheng Zhao
email: yuhengzhao@fudan.edu.cn
description: > # this means to ignore newlines until "baseurl:"
  PhD candidate from Fudan University.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.yuhengzhao.me" # the base hostname & protocol for your site
production_url: "https://www.yuhengzhao.me"
github_username: zyh1222
permalink: /blog/:year/:month/:title.html

scholar: "https://scholar.google.com/citations?user=aK_a-JoAAAAJ&hl=en"

twitter:
  username: YuhengZhao_
  url: https://twitter.com/YuhengZhao_

sass:
  style: compressed

collections:
  publications:
    output: false

jekyll-mentions:
  base_url: https://twitter.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
